# Site settings
title: xiaomenglnan
brief-intro:Front-end work books feelings love fun 
email: xiaomenglnan@126.com
description: 进阶中的前端实习生
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xiaomenglnan.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  xiaomenglnan
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false

# other links
#twitter_username: gaohaoyang126
#facebook_username: gaohaoyang.water
github_username:  xiaomenglnan
email: xiaomenglnan@126.com
weibo_username: 奋斗的小绿龟
zhihu_username: 孟令楠

description_footer: 学习前端路途之中的点点滴滴~